# Generated by Django 4.2.7 on 2024-04-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0002_reply_alter_course_id_alter_course_details_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head_movement', models.CharField(max_length=100)),
                ('left_eye', models.CharField(max_length=100)),
                ('right_eye', models.CharField(max_length=100)),
                ('head_position', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('cheating_incident', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
