# Generated by Django 4.2.7 on 2024-04-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0003_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='cheating_images',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
