# Generated by Django 4.2.7 on 2024-04-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0004_attendancerecord_cheating_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='cheating_images',
            new_name='image_path',
        ),
    ]
