# Generated by Django 4.2.7 on 2024-04-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0005_rename_cheating_images_attendancerecord_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='image_path',
            field=models.ImageField(upload_to='cheating_images/'),
        ),
    ]
