# Generated by Django 4.2.7 on 2024-04-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0008_profile_email_alter_profile_image_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='diffucalty',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
