# Generated by Django 4.2.7 on 2024-05-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0009_mcq_diffucalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
