# Generated by Django 4.2.7 on 2024-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0010_profile_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='levelOfExam',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='marks',
            field=models.CharField(default='', max_length=100),
        ),
    ]
