# Generated by Django 4.2.7 on 2024-05-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0011_profile_levelofexam_profile_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='image_path',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='multiple_persons',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='cheating_incident',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='head_movement',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='head_position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='left_eye',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='right_eye',
            field=models.CharField(max_length=50),
        ),
    ]
