# Generated by Django 4.2.7 on 2024-05-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0012_remove_attendancerecord_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='multiple_persons',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
