# Generated by Django 4.2.7 on 2024-05-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0013_alter_attendancerecord_multiple_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='multiple_persons',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='image_path',
            field=models.ImageField(default='', upload_to='cheating_images/'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='cheating_incident',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='head_movement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='head_position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='left_eye',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
