# Generated by Django 4.2.7 on 2024-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0014_remove_attendancerecord_multiple_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='sound_detection',
            field=models.CharField(default='', max_length=10),
        ),
    ]
