# Generated by Django 4.2.7 on 2024-05-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0015_attendancerecord_sound_detection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='right_eye',
        ),
    ]
