# Generated by Django 4.2.7 on 2024-05-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0016_remove_attendancerecord_right_eye'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='right_eye',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
