# Generated by Django 4.2.7 on 2024-05-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0017_attendancerecord_right_eye'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='background_noise_level',
            field=models.CharField(default='', max_length=20),
        ),
    ]
